version: "3"
services:
   mongo: 
      image: mongo
      container_name: mongo
      volumes:
          - data:/data/db
   backend:
      build:  ./backend
      ports:
       - "5000:5000"  
      depends_on:
         - mongo
   frontend:
      build: ./frontend
      ports: 
        - "5001:80" 
      depends_on:
         - mongo
         - backend

volumes:
   - data:
            

