apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-username: YWRtaW4=          # admin
  mongo-password: YWRtaW4xMjM=      # admin123
  mongo-database: dG9kbw==          # todo
